Extend base html
Mr-3rd/MCTC_ITEC2905_fall2023_proj3_team03_Justin_Amy_Peng pull request #46
Opened 2023-10-18 22:00 UTC by pengxuemoua

Extend base html inheritance. 

Updated CSS

Center aligned the data on car_recalls.html.

Still a work in progress, but this is a step in the right direction. 

Sending for approval to merge into main. @Mr-3rd @amylynndee 

Pertaining to issue #45

2023-10-18 22:50 UTC, amylynndee commented
@pengxuemoua the styling looks really good, I noticed the reset button is gone, are we going without it going forward?

2023-10-18 22:54 UTC, Mr-3rd requested changes
@pengxuemoua I have one small change so far, working on reviewing now

2023-10-18 22:54 UTC, Mr-3rd commented on static/cars_style.css
> +    text-align: center;
@pengxuemoua Can we change this to `display: table;`

This has all of the items connecting to their bullet points. My centered view was very distorted

2023-10-19 00:10 UTC, amylynndee commented
witnessed @Mr-3rd update code, everything looks good and works, we are good to merge!

2023-10-19 00:11 UTC, merged